services:
  wakapi_postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${WAKAPI_DB_CONTAINER}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}

    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

    networks:
      - wakapi_net


  wakapi_app:
    image: ${WAKAPI_IMAGE}
    container_name: ${WAKAPI_APP_CONTAINER}
    restart: unless-stopped

    depends_on:
      - wakapi_postgres

    environment:
      TZ: ${TZ}

      WAKAPI_PUBLIC_URL: ${WAKAPI_PUBLIC_URL}

      WAKAPI_ALLOW_SIGNUP: ${WAKAPI_ALLOW_SIGNUP}
      WAKAPI_COOKIE_SECURE: ${WAKAPI_COOKIE_SECURE}
      WAKAPI_LOG_LEVEL: ${WAKAPI_LOG_LEVEL}

      WAKAPI_DB_TYPE: ${DB_TYPE}
      WAKAPI_DB_HOST: ${DB_HOST}
      WAKAPI_DB_PORT: ${DB_PORT}
      WAKAPI_DB_NAME: ${DB_NAME}
      WAKAPI_DB_USER: ${DB_USER}
      WAKAPI_DB_PASSWORD: ${DB_PASSWORD}
      WAKAPI_DB_SSL: ${DB_SSL}

    networks:
      - wakapi_net

    ports:
      - "127.0.0.1:${WAKAPI_PORT}:3000"

networks:
  wakapi_net:
    name: ${WAKAPI_NETWORK}

volumes:
  wakapi_pgdata:
    name: ${POSTGRES_VOLUME}
